import prodSikkens from "@/assets/prod-sikkens.jpg";
import prodSigma from "@/assets/prod-sigma.jpg";
import prodWijzonol from "@/assets/prod-wijzonol.jpg";
import prodFlexa from "@/assets/prod-flexa.jpg";

export type Product = {
  id: string;
  slug: string;
  name: string;
  brand: string;
  category: "muurverf" | "lakverf" | "beits" | "grondverf" | "buitenverf" | "benodigdheden";
  price: number;
  oldPrice?: number;
  image: string;
  rating: number;
  reviews: number;
  inStock: boolean;
  isNew?: boolean;
  bestseller?: boolean;
  applications: string[]; // binnen / buiten / hout / metaal / muur
  finish?: "mat" | "zijdeglans" | "hoogglans" | "satijn";
  volume?: string; // "2,5 L"
  coverage?: number; // m² per liter
  shortDescription: string;
};

export const PRODUCTS: Product[] = [
  {
    id: "p-001",
    slug: "sikkens-alphacryl-pure-mat-sf-2-5l",
    name: "Sikkens Alphacryl Pure Mat SF",
    brand: "Sikkens",
    category: "muurverf",
    price: 44.95,
    oldPrice: 52.0,
    image: prodSikkens,
    rating: 4.8,
    reviews: 128,
    inStock: true,
    bestseller: true,
    applications: ["binnen", "muur", "plafond"],
    finish: "mat",
    volume: "2,5 L",
    coverage: 10,
    shortDescription: "Professionele muurverf met diepmatte afwerking en perfecte dekking.",
  },
  {
    id: "p-002",
    slug: "sigma-s2u-allure-gloss-2-5l",
    name: "Sigma S2U Allure Gloss",
    brand: "Sigma",
    category: "lakverf",
    price: 49.95,
    image: prodSigma,
    rating: 4.7,
    reviews: 96,
    inStock: true,
    bestseller: true,
    applications: ["binnen", "buiten", "hout", "metaal"],
    finish: "hoogglans",
    volume: "2,5 L",
    coverage: 12,
    shortDescription: "Hoogwaardige hoogglans lakverf voor binnen- en buitenwerk.",
  },
  {
    id: "p-003",
    slug: "wijzonol-lbh-sdt-ultra-hoogglans-2-5l",
    name: "Wijzonol LBH SDT Ultra Hoogglans",
    brand: "Wijzonol",
    category: "lakverf",
    price: 39.5,
    image: prodWijzonol,
    rating: 4.6,
    reviews: 74,
    inStock: true,
    bestseller: true,
    applications: ["binnen", "hout"],
    finish: "hoogglans",
    volume: "2,5 L",
    coverage: 12,
    shortDescription: "Strakke hoogglanslak met uitstekende vloei en duurzaamheid.",
  },
  {
    id: "p-004",
    slug: "flexa-powerdek-muurverf-mat-2-5l",
    name: "Flexa Powerdek Muurverf Mat",
    brand: "Flexa",
    category: "muurverf",
    price: 42.95,
    image: prodFlexa,
    rating: 4.5,
    reviews: 85,
    inStock: true,
    bestseller: true,
    applications: ["binnen", "muur"],
    finish: "mat",
    volume: "2,5 L",
    coverage: 10,
    shortDescription: "Extra dekkende muurverf — vaak in één laag klaar.",
  },
  {
    id: "p-005",
    slug: "sikkens-rubbol-bl-rezisto-satin-1l",
    name: "Sikkens Rubbol BL Rezisto Satin",
    brand: "Sikkens",
    category: "lakverf",
    price: 34.5,
    image: prodSikkens,
    rating: 4.7,
    reviews: 52,
    inStock: true,
    isNew: true,
    applications: ["binnen", "hout", "metaal"],
    finish: "satijn",
    volume: "1 L",
    coverage: 11,
    shortDescription: "Krasvaste satijnlak voor intensief gebruikte oppervlakken.",
  },
  {
    id: "p-006",
    slug: "sigma-perfect-matt-5l",
    name: "Sigma Perfect Matt",
    brand: "Sigma",
    category: "muurverf",
    price: 64.95,
    image: prodSigma,
    rating: 4.6,
    reviews: 41,
    inStock: true,
    isNew: true,
    applications: ["binnen", "muur", "plafond"],
    finish: "mat",
    volume: "5 L",
    coverage: 11,
    shortDescription: "Diepmatte muurverf met fluweelzachte uitstraling.",
  },
  {
    id: "p-007",
    slug: "wijzonol-grondverf-universeel-2-5l",
    name: "Wijzonol Universele Grondverf",
    brand: "Wijzonol",
    category: "grondverf",
    price: 28.95,
    image: prodWijzonol,
    rating: 4.4,
    reviews: 33,
    inStock: true,
    applications: ["binnen", "buiten", "hout", "metaal"],
    volume: "2,5 L",
    coverage: 9,
    shortDescription: "Hechtende grondverf voor vrijwel alle ondergronden.",
  },
  {
    id: "p-008",
    slug: "flexa-buitenlak-zijdeglans-2-5l",
    name: "Flexa Buitenlak Zijdeglans",
    brand: "Flexa",
    category: "buitenverf",
    price: 46.95,
    image: prodFlexa,
    rating: 4.5,
    reviews: 28,
    inStock: true,
    applications: ["buiten", "hout"],
    finish: "zijdeglans",
    volume: "2,5 L",
    coverage: 11,
    shortDescription: "Weerbestendige zijdeglanslak voor buitenwerk.",
  },
  {
    id: "p-009",
    slug: "sigma-decor-beits-transparant-2-5l",
    name: "Sigma Decor Beits Transparant",
    brand: "Sigma",
    category: "beits",
    price: 36.5,
    image: prodSigma,
    rating: 4.3,
    reviews: 19,
    inStock: false,
    applications: ["buiten", "hout"],
    volume: "2,5 L",
    coverage: 10,
    shortDescription: "Transparante beits die de houtnerf prachtig laat uitkomen.",
  },
  {
    id: "p-010",
    slug: "sikkens-cetol-thb-plus-1l",
    name: "Sikkens Cetol THB Plus",
    brand: "Sikkens",
    category: "beits",
    price: 31.95,
    image: prodSikkens,
    rating: 4.7,
    reviews: 64,
    inStock: true,
    applications: ["buiten", "hout"],
    volume: "1 L",
    coverage: 14,
    shortDescription: "Dekkende beits met topbescherming tegen weer en wind.",
  },
  {
    id: "p-011",
    slug: "wijzonol-binnenmuurverf-mat-5l",
    name: "Wijzonol Binnenmuurverf Mat",
    brand: "Wijzonol",
    category: "muurverf",
    price: 54.95,
    image: prodWijzonol,
    rating: 4.5,
    reviews: 47,
    inStock: true,
    applications: ["binnen", "muur", "plafond"],
    finish: "mat",
    volume: "5 L",
    coverage: 10,
    shortDescription: "Goed dekkende matte muurverf met prettige verwerking.",
  },
  {
    id: "p-012",
    slug: "flexa-binnenlak-zijdeglans-750ml",
    name: "Flexa Binnenlak Zijdeglans",
    brand: "Flexa",
    category: "lakverf",
    price: 22.95,
    image: prodFlexa,
    rating: 4.4,
    reviews: 36,
    inStock: true,
    applications: ["binnen", "hout", "metaal"],
    finish: "zijdeglans",
    volume: "750 ml",
    coverage: 11,
    shortDescription: "Reukarme watergedragen lak met strakke zijdeglans-afwerking.",
  },
  {
    id: "p-013",
    slug: "histor-perfect-base-grondverf-2-5l",
    name: "Histor Perfect Base Grondverf",
    brand: "Histor",
    category: "grondverf",
    price: 32.5,
    image: prodWijzonol,
    rating: 4.6,
    reviews: 58,
    inStock: true,
    applications: ["binnen", "buiten", "hout", "metaal"],
    volume: "2,5 L",
    coverage: 10,
    shortDescription: "Universele hechtprimer voor vrijwel elke ondergrond.",
  },
  {
    id: "p-014",
    slug: "histor-schone-muur-mat-5l",
    name: "Histor Schone Muur Muurverf Mat",
    brand: "Histor",
    category: "muurverf",
    price: 49.95,
    image: prodSigma,
    rating: 4.5,
    reviews: 41,
    inStock: true,
    applications: ["binnen", "muur"],
    finish: "mat",
    volume: "5 L",
    coverage: 11,
    shortDescription: "Reinigbare matte muurverf, ideaal voor hal en woonkamer.",
  },
  {
    id: "p-015",
    slug: "histor-cabinet-paint-zijdeglans-750ml",
    name: "Histor Cabinet Paint Zijdeglans",
    brand: "Histor",
    category: "lakverf",
    price: 27.95,
    image: prodFlexa,
    rating: 4.7,
    reviews: 73,
    inStock: true,
    isNew: true,
    applications: ["binnen", "hout"],
    finish: "zijdeglans",
    volume: "750 ml",
    coverage: 11,
    shortDescription: "Speciale meubel- en kastenlak met krasvaste afwerking.",
  },
  {
    id: "p-016",
    slug: "farrow-ball-estate-emulsion-2-5l",
    name: "Farrow & Ball Estate Emulsion",
    brand: "Farrow & Ball",
    category: "muurverf",
    price: 92.0,
    image: prodSikkens,
    rating: 4.9,
    reviews: 112,
    inStock: true,
    bestseller: true,
    applications: ["binnen", "muur"],
    finish: "mat",
    volume: "2,5 L",
    coverage: 12,
    shortDescription: "Iconische diepmatte muurverf met fluweelzachte uitstraling.",
  },
  {
    id: "p-017",
    slug: "farrow-ball-modern-eggshell-2-5l",
    name: "Farrow & Ball Modern Eggshell",
    brand: "Farrow & Ball",
    category: "lakverf",
    price: 98.5,
    image: prodWijzonol,
    rating: 4.8,
    reviews: 64,
    inStock: true,
    applications: ["binnen", "hout", "metaal"],
    finish: "satijn",
    volume: "2,5 L",
    coverage: 12,
    shortDescription: "Slijtvaste satijnlak voor deuren, kozijnen en lambrisering.",
  },
  {
    id: "p-018",
    slug: "farrow-ball-exterior-masonry-5l",
    name: "Farrow & Ball Exterior Masonry",
    brand: "Farrow & Ball",
    category: "buitenverf",
    price: 145.0,
    image: prodSigma,
    rating: 4.7,
    reviews: 29,
    inStock: true,
    applications: ["buiten", "muur"],
    finish: "mat",
    volume: "5 L",
    coverage: 9,
    shortDescription: "Ademende buitenmuurverf met 15 jaar weerbescherming.",
  },
  {
    id: "p-019",
    slug: "benjamin-moore-regal-select-mat-3-8l",
    name: "Benjamin Moore Regal Select Matt",
    brand: "Benjamin Moore",
    category: "muurverf",
    price: 79.95,
    image: prodSigma,
    rating: 4.8,
    reviews: 88,
    inStock: true,
    bestseller: true,
    applications: ["binnen", "muur", "plafond"],
    finish: "mat",
    volume: "3,8 L",
    coverage: 11,
    shortDescription: "Extreem dekkende premium muurverf met zuivere kleurweergave.",
  },
  {
    id: "p-020",
    slug: "benjamin-moore-advance-satin-946ml",
    name: "Benjamin Moore Advance Satin",
    brand: "Benjamin Moore",
    category: "lakverf",
    price: 49.95,
    image: prodFlexa,
    rating: 4.7,
    reviews: 54,
    inStock: true,
    applications: ["binnen", "hout", "metaal"],
    finish: "satijn",
    volume: "946 ml",
    coverage: 12,
    shortDescription: "Watergedragen alkydlak met de strakheid van traditionele olielak.",
  },
  {
    id: "p-021",
    slug: "benjamin-moore-aura-bath-spa-946ml",
    name: "Benjamin Moore Aura Bath & Spa",
    brand: "Benjamin Moore",
    category: "muurverf",
    price: 64.5,
    image: prodSikkens,
    rating: 4.8,
    reviews: 42,
    inStock: true,
    isNew: true,
    applications: ["binnen", "muur"],
    finish: "mat",
    volume: "946 ml",
    coverage: 10,
    shortDescription: "Vochtbestendige muurverf speciaal voor badkamer en keuken.",
  },
  {
    id: "p-022",
    slug: "dulux-diamond-matt-5l",
    name: "Dulux Diamond Matt",
    brand: "Dulux",
    category: "muurverf",
    price: 58.95,
    image: prodSigma,
    rating: 4.6,
    reviews: 102,
    inStock: true,
    bestseller: true,
    applications: ["binnen", "muur", "plafond"],
    finish: "mat",
    volume: "5 L",
    coverage: 12,
    shortDescription: "Sterke, afwasbare matte muurverf voor intensief gebruik.",
  },
  {
    id: "p-023",
    slug: "dulux-weathershield-smooth-5l",
    name: "Dulux Weathershield Smooth Masonry",
    brand: "Dulux",
    category: "buitenverf",
    price: 74.95,
    image: prodFlexa,
    rating: 4.5,
    reviews: 47,
    inStock: true,
    applications: ["buiten", "muur"],
    finish: "mat",
    volume: "5 L",
    coverage: 8,
    shortDescription: "Buitenmuurverf met 15 jaar bescherming tegen regen en algen.",
  },
  {
    id: "p-024",
    slug: "dulux-quick-dry-satinwood-750ml",
    name: "Dulux Quick Dry Satinwood",
    brand: "Dulux",
    category: "lakverf",
    price: 24.95,
    image: prodWijzonol,
    rating: 4.4,
    reviews: 39,
    inStock: true,
    applications: ["binnen", "hout"],
    finish: "satijn",
    volume: "750 ml",
    coverage: 13,
    shortDescription: "Sneldrogende watergedragen lak voor hout binnenshuis.",
  },
  {
    id: "p-025",
    slug: "progold-premium-muurverf-mat-10l",
    name: "ProGold Premium Muurverf Mat",
    brand: "ProGold",
    category: "muurverf",
    price: 79.95,
    oldPrice: 94.5,
    image: prodSikkens,
    rating: 4.5,
    reviews: 68,
    inStock: true,
    bestseller: true,
    applications: ["binnen", "muur", "plafond"],
    finish: "mat",
    volume: "10 L",
    coverage: 11,
    shortDescription: "Voordelige professionele muurverf in grootverpakking.",
  },
  {
    id: "p-026",
    slug: "progold-aqua-grondverf-2-5l",
    name: "ProGold Aqua Grondverf",
    brand: "ProGold",
    category: "grondverf",
    price: 26.5,
    image: prodWijzonol,
    rating: 4.4,
    reviews: 31,
    inStock: true,
    applications: ["binnen", "buiten", "hout", "metaal"],
    volume: "2,5 L",
    coverage: 10,
    shortDescription: "Watergedragen hechtprimer met snelle droging.",
  },
  {
    id: "p-027",
    slug: "progold-zijdeglans-lak-universeel-1l",
    name: "ProGold Zijdeglans Lak Universeel",
    brand: "ProGold",
    category: "lakverf",
    price: 29.95,
    image: prodFlexa,
    rating: 4.5,
    reviews: 44,
    inStock: true,
    applications: ["binnen", "buiten", "hout", "metaal"],
    finish: "zijdeglans",
    volume: "1 L",
    coverage: 12,
    shortDescription: "Veelzijdige zijdeglanslak voor binnen- en buitenwerk.",
  },
  {
    id: "p-028",
    slug: "trimetal-polyurethane-satin-1l",
    name: "Trimetal Polyurethane Satin",
    brand: "Trimetal",
    category: "lakverf",
    price: 42.95,
    image: prodWijzonol,
    rating: 4.7,
    reviews: 36,
    inStock: true,
    applications: ["binnen", "hout", "metaal"],
    finish: "satijn",
    volume: "1 L",
    coverage: 12,
    shortDescription: "Premium polyurethaanlak met slijtvaste satin-afwerking.",
  },
  {
    id: "p-029",
    slug: "trimetal-decor-mat-2-5l",
    name: "Trimetal Décor Mat",
    brand: "Trimetal",
    category: "muurverf",
    price: 48.5,
    image: prodSigma,
    rating: 4.6,
    reviews: 22,
    inStock: true,
    isNew: true,
    applications: ["binnen", "muur"],
    finish: "mat",
    volume: "2,5 L",
    coverage: 11,
    shortDescription: "Diepmatte muurverf met uitgesproken kleurintensiteit.",
  },
  {
    id: "p-030",
    slug: "trimetal-cryltane-buitenlak-2-5l",
    name: "Trimetal Cryltane Buitenlak",
    brand: "Trimetal",
    category: "buitenverf",
    price: 64.95,
    image: prodFlexa,
    rating: 4.6,
    reviews: 27,
    inStock: true,
    applications: ["buiten", "hout", "metaal"],
    finish: "zijdeglans",
    volume: "2,5 L",
    coverage: 11,
    shortDescription: "UV-bestendige buitenlak met lange standtijd.",
  },
];

export const BRANDS = ["Sikkens", "Sigma", "Wijzonol", "Flexa", "Histor", "Farrow & Ball", "Benjamin Moore", "Dulux", "ProGold", "Trimetal"] as const;

export const CATEGORIES: { key: Product["category"]; label: string }[] = [
  { key: "muurverf", label: "Muurverf" },
  { key: "lakverf", label: "Lakverf" },
  { key: "beits", label: "Beits" },
  { key: "grondverf", label: "Grondverf" },
  { key: "buitenverf", label: "Buitenverf" },
  { key: "benodigdheden", label: "Verfbenodigdheden" },
];

export const CATEGORY_INFO: Record<Product["category"], {
  intro: string;
  whenToUse: string[];
  tips: string[];
  metaDescription: string;
}> = {
  muurverf: {
    intro:
      "Muurverf vormt de basis van elk interieur. Of je nu een fluweelmatte uitstraling wilt of een afwasbare muur voor hal en keuken — een goede muurverf dekt in één à twee lagen, vloeit egaal uit en houdt jarenlang z'n kleur.",
    whenToUse: [
      "Woon- en slaapkamermuren met een rustige, matte uitstraling",
      "Hal, gang en keuken waar afwasbaarheid telt",
      "Plafonds — kies altijd voor een diepmat plafondverf zonder glansreflectie",
    ],
    tips: [
      "Schuur glanzende muren licht op en stof goed af voor optimale hechting",
      "Gebruik een primer op kale gips, nieuwe stuc of sterk zuigende ondergronden",
      "Twee dunne lagen geven altijd een mooier resultaat dan één dikke laag",
    ],
    metaDescription:
      "Muurverf van Sikkens, Sigma, Flexa, Histor en meer. Mat, afwasbaar of zijdeglans — in elke kleur gemengd. Voor 21:00 besteld, morgen in huis.",
  },
  lakverf: {
    intro:
      "Lakverf beschermt en verfraait hout en metaal binnen- én buitenshuis. Van krasvaste meubel- en deurenlak tot weerbestendige kozijnlak: kies de juiste afwerking (mat, satijn, zijdeglans of hoogglans) voor het beste resultaat.",
    whenToUse: [
      "Deuren, kozijnen, plinten en trapleuningen binnenshuis",
      "Meubels, kasten en houten panelen die intensief gebruikt worden",
      "Radiatoren en metalen elementen (met de juiste primer)",
    ],
    tips: [
      "Werk altijd in dunne lagen — dikke lagen geven loopneuzen en langere droogtijd",
      "Schuur tussen lagen licht op met korrel 240 voor een glad eindresultaat",
      "Watergedragen lak is reukarm en vergeelt niet; ideaal voor binnen",
    ],
    metaDescription:
      "Lakverf voor hout en metaal: mat, satijn, zijdeglans en hoogglans. Topmerken zoals Sikkens, Sigma en Wijzonol. Snel geleverd en op kleur gemengd.",
  },
  beits: {
    intro:
      "Beits laat de natuurlijke houtnerf zichtbaar en beschermt tegelijk tegen vocht, UV en vervuiling. Kies transparant voor een naturel uiterlijk, of dekkend voor maximale levensduur buitenshuis.",
    whenToUse: [
      "Houten gevels, schuttingen en tuinhuizen",
      "Boeidelen, kozijnen en buitendeuren van hout",
      "Tuinmeubelen en pergola's",
    ],
    tips: [
      "Verwijder oude losse beits altijd grondig voor opnieuw aanbrengen",
      "Werk bij voorkeur niet in volle zon — de beits trekt dan te snel in",
      "Plan onderhoud elke 3 tot 5 jaar in afhankelijk van weersinvloeden",
    ],
    metaDescription:
      "Beits voor binnen en buiten: transparant of dekkend. Sikkens Cetol, Sigma Decor en meer. Bescherm hout duurzaam tegen weer en wind.",
  },
  grondverf: {
    intro:
      "Grondverf is de basislaag die zorgt voor optimale hechting, egalisatie en een lagere verfopname. Sla deze stap nooit over op kaal hout, metaal of een sterk zuigende ondergrond.",
    whenToUse: [
      "Kaal of nieuw hout dat nog niet eerder geschilderd is",
      "Metaal (gebruik dan altijd een roestwerende primer)",
      "Vlekkerige, sterk zuigende of nicotine-bedekte ondergronden",
    ],
    tips: [
      "Stof en ontvet de ondergrond grondig voor je grondverf aanbrengt",
      "Schuur na het drogen licht op voor de beste hechting van de aflak",
      "Kies een grondverf in een kleur die dicht bij je eindkleur ligt",
    ],
    metaDescription:
      "Grondverf en primers voor hout, metaal en moeilijke ondergronden. Universele hechtprimers van Sikkens, Wijzonol, Histor en meer.",
  },
  buitenverf: {
    intro:
      "Buitenverf moet meer kunnen: bestand zijn tegen UV, regen, vorst en temperatuurschommelingen. Onze buitenlakken en gevelverven zijn formuleerd voor jarenlange standtijd onder alle weersomstandigheden.",
    whenToUse: [
      "Kozijnen, deuren en boeidelen van hout",
      "Gevels, tuinmuren en buitenmuurvlakken",
      "Tuinhekken, schuttingen en buitenmeubelen",
    ],
    tips: [
      "Schilder bij minimaal 8 °C en droog weer — controleer de weersvoorspelling",
      "Werk altijd met grondverf én twee lagen aflak voor maximale bescherming",
      "Vermijd directe zon op het te schilderen vlak (blaasvorming)",
    ],
    metaDescription:
      "Buitenverf voor kozijnen, gevels en houtwerk. Weerbestendige lakken en muurverven van Farrow & Ball, Dulux, Flexa en Trimetal.",
  },
  benodigdheden: {
    intro:
      "Goed gereedschap maakt het verfwerk twee keer zo prettig. Van kwaliteitskwasten en microvezelrollers tot afplaktape, schuurpapier en afdekzeil — alles wat je nodig hebt voor een strak eindresultaat.",
    whenToUse: [
      "Voorbereiding: schuurpapier, plamuur, afplaktape en afdekzeil",
      "Aanbrengen: kwasten, rollers, verfbakken en verlengstelen",
      "Afwerking: krimpfolie, kwastreiniger en opbergblikjes",
    ],
    tips: [
      "Investeer in goede kwasten — ze geven minder strepen en gaan jaren mee",
      "Microvezelroller voor muurverf, schuimroller voor lak op vlakke vlakken",
      "Reinig kwasten direct na gebruik; uitgeharde verf is niet te verwijderen",
    ],
    metaDescription:
      "Verfbenodigdheden: kwasten, rollers, afplaktape, schuurpapier en afdekmateriaal. Alles voor een professioneel verfresultaat.",
  },
};

export const POPULAR_RAL = [
  { code: "RAL 9010", name: "Zuiver wit", hex: "#F1ECE0" },
  { code: "RAL 9016", name: "Verkeerswit", hex: "#F1F1F1" },
  { code: "RAL 7016", name: "Antracietgrijs", hex: "#293133" },
  { code: "RAL 9005", name: "Gitzwart", hex: "#0A0A0A" },
  { code: "RAL 7035", name: "Lichtgrijs", hex: "#CBD0CC" },
  { code: "RAL 6005", name: "Mosgroen", hex: "#2F4538" },
];

export function formatPrice(n: number) {
  return `€${n.toFixed(2).replace(".", ",")}`;
}

export function searchCatalog(q: string, limit = 8) {
  const query = q.trim().toLowerCase();
  if (!query) return { products: [], brands: [], categories: [], ral: [] };

  const products = PRODUCTS.filter((p) =>
    [p.name, p.brand, p.category, ...p.applications].some((v) =>
      v.toLowerCase().includes(query),
    ),
  ).slice(0, limit);

  const brands = BRANDS.filter((b) => b.toLowerCase().includes(query)).slice(0, 4);

  const categories = CATEGORIES.filter(
    (c) => c.label.toLowerCase().includes(query) || c.key.includes(query),
  ).slice(0, 4);

  const ral = POPULAR_RAL.filter(
    (r) => r.code.toLowerCase().includes(query) || r.name.toLowerCase().includes(query),
  ).slice(0, 4);

  return { products, brands, categories, ral };
}
