/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MuurverfRouteImport } from './routes/muurverf'
import { Route as IndexRouteImport } from './routes/index'

const MuurverfRoute = MuurverfRouteImport.update({
  id: '/muurverf',
  path: '/muurverf',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/muurverf': typeof MuurverfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/muurverf': typeof MuurverfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/muurverf': typeof MuurverfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/muurverf'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/muurverf'
  id: '__root__' | '/' | '/muurverf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MuurverfRoute: typeof MuurverfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/muurverf': {
      id: '/muurverf'
      path: '/muurverf'
      fullPath: '/muurverf'
      preLoaderRoute: typeof MuurverfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MuurverfRoute: MuurverfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
