/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZoekenRouteImport } from './routes/zoeken'
import { Route as WinkelwagenRouteImport } from './routes/winkelwagen'
import { Route as VerfmengserviceRouteImport } from './routes/verfmengservice'
import { Route as VerfcalculatorRouteImport } from './routes/verfcalculator'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RalRouteImport } from './routes/ral'
import { Route as MuurverfRouteImport } from './routes/muurverf'
import { Route as HulpEnAdviesRouteImport } from './routes/hulp-en-advies'
import { Route as DemonstratiesRouteImport } from './routes/demonstraties'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BestellingBevestigdRouteImport } from './routes/bestelling-bevestigd'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AfrekenenRouteImport } from './routes/afrekenen'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RalCodeRouteImport } from './routes/ral.$code'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CategorieSlugRouteImport } from './routes/categorie.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminBrandsRouteImport } from './routes/_authenticated/admin.brands'

const ZoekenRoute = ZoekenRouteImport.update({
  id: '/zoeken',
  path: '/zoeken',
  getParentRoute: () => rootRouteImport,
} as any)
const WinkelwagenRoute = WinkelwagenRouteImport.update({
  id: '/winkelwagen',
  path: '/winkelwagen',
  getParentRoute: () => rootRouteImport,
} as any)
const VerfmengserviceRoute = VerfmengserviceRouteImport.update({
  id: '/verfmengservice',
  path: '/verfmengservice',
  getParentRoute: () => rootRouteImport,
} as any)
const VerfcalculatorRoute = VerfcalculatorRouteImport.update({
  id: '/verfcalculator',
  path: '/verfcalculator',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RalRoute = RalRouteImport.update({
  id: '/ral',
  path: '/ral',
  getParentRoute: () => rootRouteImport,
} as any)
const MuurverfRoute = MuurverfRouteImport.update({
  id: '/muurverf',
  path: '/muurverf',
  getParentRoute: () => rootRouteImport,
} as any)
const HulpEnAdviesRoute = HulpEnAdviesRouteImport.update({
  id: '/hulp-en-advies',
  path: '/hulp-en-advies',
  getParentRoute: () => rootRouteImport,
} as any)
const DemonstratiesRoute = DemonstratiesRouteImport.update({
  id: '/demonstraties',
  path: '/demonstraties',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BestellingBevestigdRoute = BestellingBevestigdRouteImport.update({
  id: '/bestelling-bevestigd',
  path: '/bestelling-bevestigd',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AfrekenenRoute = AfrekenenRouteImport.update({
  id: '/afrekenen',
  path: '/afrekenen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RalCodeRoute = RalCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => RalRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorieSlugRoute = CategorieSlugRouteImport.update({
  id: '/categorie/$slug',
  path: '/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAdminBrandsRoute =
  AuthenticatedAdminBrandsRouteImport.update({
    id: '/admin/brands',
    path: '/admin/brands',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afrekenen': typeof AfrekenenRoute
  '/auth': typeof AuthRoute
  '/bestelling-bevestigd': typeof BestellingBevestigdRoute
  '/blog': typeof BlogRouteWithChildren
  '/demonstraties': typeof DemonstratiesRoute
  '/hulp-en-advies': typeof HulpEnAdviesRoute
  '/muurverf': typeof MuurverfRoute
  '/ral': typeof RalRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verfcalculator': typeof VerfcalculatorRoute
  '/verfmengservice': typeof VerfmengserviceRoute
  '/winkelwagen': typeof WinkelwagenRoute
  '/zoeken': typeof ZoekenRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/ral/$code': typeof RalCodeRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afrekenen': typeof AfrekenenRoute
  '/auth': typeof AuthRoute
  '/bestelling-bevestigd': typeof BestellingBevestigdRoute
  '/blog': typeof BlogRouteWithChildren
  '/demonstraties': typeof DemonstratiesRoute
  '/hulp-en-advies': typeof HulpEnAdviesRoute
  '/muurverf': typeof MuurverfRoute
  '/ral': typeof RalRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verfcalculator': typeof VerfcalculatorRoute
  '/verfmengservice': typeof VerfmengserviceRoute
  '/winkelwagen': typeof WinkelwagenRoute
  '/zoeken': typeof ZoekenRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/ral/$code': typeof RalCodeRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/afrekenen': typeof AfrekenenRoute
  '/auth': typeof AuthRoute
  '/bestelling-bevestigd': typeof BestellingBevestigdRoute
  '/blog': typeof BlogRouteWithChildren
  '/demonstraties': typeof DemonstratiesRoute
  '/hulp-en-advies': typeof HulpEnAdviesRoute
  '/muurverf': typeof MuurverfRoute
  '/ral': typeof RalRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verfcalculator': typeof VerfcalculatorRoute
  '/verfmengservice': typeof VerfmengserviceRoute
  '/winkelwagen': typeof WinkelwagenRoute
  '/zoeken': typeof ZoekenRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/ral/$code': typeof RalCodeRoute
  '/_authenticated/admin/brands': typeof AuthenticatedAdminBrandsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/afrekenen'
    | '/auth'
    | '/bestelling-bevestigd'
    | '/blog'
    | '/demonstraties'
    | '/hulp-en-advies'
    | '/muurverf'
    | '/ral'
    | '/sitemap.xml'
    | '/verfcalculator'
    | '/verfmengservice'
    | '/winkelwagen'
    | '/zoeken'
    | '/blog/$slug'
    | '/categorie/$slug'
    | '/product/$slug'
    | '/ral/$code'
    | '/admin/brands'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/afrekenen'
    | '/auth'
    | '/bestelling-bevestigd'
    | '/blog'
    | '/demonstraties'
    | '/hulp-en-advies'
    | '/muurverf'
    | '/ral'
    | '/sitemap.xml'
    | '/verfcalculator'
    | '/verfmengservice'
    | '/winkelwagen'
    | '/zoeken'
    | '/blog/$slug'
    | '/categorie/$slug'
    | '/product/$slug'
    | '/ral/$code'
    | '/admin/brands'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/afrekenen'
    | '/auth'
    | '/bestelling-bevestigd'
    | '/blog'
    | '/demonstraties'
    | '/hulp-en-advies'
    | '/muurverf'
    | '/ral'
    | '/sitemap.xml'
    | '/verfcalculator'
    | '/verfmengservice'
    | '/winkelwagen'
    | '/zoeken'
    | '/blog/$slug'
    | '/categorie/$slug'
    | '/product/$slug'
    | '/ral/$code'
    | '/_authenticated/admin/brands'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AfrekenenRoute: typeof AfrekenenRoute
  AuthRoute: typeof AuthRoute
  BestellingBevestigdRoute: typeof BestellingBevestigdRoute
  BlogRoute: typeof BlogRouteWithChildren
  DemonstratiesRoute: typeof DemonstratiesRoute
  HulpEnAdviesRoute: typeof HulpEnAdviesRoute
  MuurverfRoute: typeof MuurverfRoute
  RalRoute: typeof RalRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerfcalculatorRoute: typeof VerfcalculatorRoute
  VerfmengserviceRoute: typeof VerfmengserviceRoute
  WinkelwagenRoute: typeof WinkelwagenRoute
  ZoekenRoute: typeof ZoekenRoute
  CategorieSlugRoute: typeof CategorieSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zoeken': {
      id: '/zoeken'
      path: '/zoeken'
      fullPath: '/zoeken'
      preLoaderRoute: typeof ZoekenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winkelwagen': {
      id: '/winkelwagen'
      path: '/winkelwagen'
      fullPath: '/winkelwagen'
      preLoaderRoute: typeof WinkelwagenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verfmengservice': {
      id: '/verfmengservice'
      path: '/verfmengservice'
      fullPath: '/verfmengservice'
      preLoaderRoute: typeof VerfmengserviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verfcalculator': {
      id: '/verfcalculator'
      path: '/verfcalculator'
      fullPath: '/verfcalculator'
      preLoaderRoute: typeof VerfcalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ral': {
      id: '/ral'
      path: '/ral'
      fullPath: '/ral'
      preLoaderRoute: typeof RalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muurverf': {
      id: '/muurverf'
      path: '/muurverf'
      fullPath: '/muurverf'
      preLoaderRoute: typeof MuurverfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hulp-en-advies': {
      id: '/hulp-en-advies'
      path: '/hulp-en-advies'
      fullPath: '/hulp-en-advies'
      preLoaderRoute: typeof HulpEnAdviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demonstraties': {
      id: '/demonstraties'
      path: '/demonstraties'
      fullPath: '/demonstraties'
      preLoaderRoute: typeof DemonstratiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestelling-bevestigd': {
      id: '/bestelling-bevestigd'
      path: '/bestelling-bevestigd'
      fullPath: '/bestelling-bevestigd'
      preLoaderRoute: typeof BestellingBevestigdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afrekenen': {
      id: '/afrekenen'
      path: '/afrekenen'
      fullPath: '/afrekenen'
      preLoaderRoute: typeof AfrekenenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ral/$code': {
      id: '/ral/$code'
      path: '/$code'
      fullPath: '/ral/$code'
      preLoaderRoute: typeof RalCodeRouteImport
      parentRoute: typeof RalRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorie/$slug': {
      id: '/categorie/$slug'
      path: '/categorie/$slug'
      fullPath: '/categorie/$slug'
      preLoaderRoute: typeof CategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/admin/brands': {
      id: '/_authenticated/admin/brands'
      path: '/admin/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AuthenticatedAdminBrandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminBrandsRoute: typeof AuthenticatedAdminBrandsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminBrandsRoute: AuthenticatedAdminBrandsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface RalRouteChildren {
  RalCodeRoute: typeof RalCodeRoute
}

const RalRouteChildren: RalRouteChildren = {
  RalCodeRoute: RalCodeRoute,
}

const RalRouteWithChildren = RalRoute._addFileChildren(RalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AfrekenenRoute: AfrekenenRoute,
  AuthRoute: AuthRoute,
  BestellingBevestigdRoute: BestellingBevestigdRoute,
  BlogRoute: BlogRouteWithChildren,
  DemonstratiesRoute: DemonstratiesRoute,
  HulpEnAdviesRoute: HulpEnAdviesRoute,
  MuurverfRoute: MuurverfRoute,
  RalRoute: RalRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerfcalculatorRoute: VerfcalculatorRoute,
  VerfmengserviceRoute: VerfmengserviceRoute,
  WinkelwagenRoute: WinkelwagenRoute,
  ZoekenRoute: ZoekenRoute,
  CategorieSlugRoute: CategorieSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
